config/routes.rb
Authorization::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resource :users, :except => [:destroy, :edit]
  resource :sessions, :only => [:create, :destroy, :new]

  match "/profile" => "users#show", :via => :get, :as => :profile
  match "users/:id" => 'users#show', :as => :user
  match "/edit" => 'users#edit', :as => :edit
  match "/profile" => "users#update", :via => :put, :as => :update

  match "/index" => 'users#index'
  match "/log_in" => 'sessions#new', :as => :log_in
  match "/log_out" => 'sessions#destroy'
  match "/register" => 'users#new'

  match "/auth/:provider/callback" => "sessions#create"

  root :to => 'users#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not valid")
    end
  end
end

class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :auth2step, :provider, :uid, :email, :login, :password, :password_confirmation, :password_digest

  validates :login, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :length => { :within => 3..30 }
  validates :password_digest, :presence => true,
                              :confirmation => true
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false },
                    :email => true

  before_save :fields_downcase

  def self.find_by_email_or_login(value)
    User.where("email = ? OR login = ?", value, value).first
  end

  def self.authenticate_with_cookies(id, cookie_password)
    user = find_by_id(id)
    return nil  if user.nil?
    return user if user.password == cookie_password
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.login = auth["info"]["nickname"]+".twitter"
      user.email = "#{auth["info"]["nickname"]}@twitter.com"
      user.password = Faker::Lorem.words.join("")[0..10]
    end
  end

  private

  def fields_downcase
    self.email = self.email.downcase
    self.login = self.login.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
  include UsersHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    respond_to do |format|
      format.html
      format.js { render '/users/form'}
    end
  end

  def create
    if params[:provider].blank?
      user = User.find_by_email_or_login(params[:session][:email].downcase)

      if user.present? && user.authenticate(params[:session][:password])
        log_in user

        redirect_to current_user
      else
        @errors = []
        @errors << "User not found"
        respond_to do |format|
          format.html { redirect_to "log_in" }
          format.js { render '/users/form' }
        end
      end
    else
      auth = env["omniauth.auth"]
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      if user.present?
        log_in user
        redirect_to user, :notice => "Log in!"
      else
        redirect_to index_path
      end
    end
  end

  def destroy
    log_out
    redirect_to index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:show, :edit, :update]

  def show
    @user = User.find_by_id(params[:id])
    @user ||= current_user
    respond_to do |format|
      format.html
      format.js { render 'show' }
    end
  end

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js { render 'register_form' }
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in @user
      respond_to do |format|
        format.html { redirect_to current_user }
        format.js { render 'show' }
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.js { render 'register_form' }
      end
    end
  end

  def edit

  end

  def update
    if current_user.update_attributes(params[:user])
      redirect_to profile_path
    else
      render "edit"
    end
  end

  private

  def authenticate
    unless logged_in?
      @user = User.new
      respond_to do |format|
        format.html { redirect_to log_in_path}
        format.js { render 'form'}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.password]
    self.current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  private

  def current_user=(user)
    @current_user = user
  end

  def user_from_remember_token
    User.authenticate_with_cookies(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    image_tag "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?d=wavatar"
  end

end

app/views/application/_form.html.slim
a#modalButton href="#myModal" role="button" class="btn" data-toggle="modal" style="display:none"

#myModal.modal tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-header
    button type="button" id="closeButton" class="close" data-dismiss="modal" aria-hidden="true" &times
    h1 Log in
  .modal-body

    = form_for(:session, :remote=>true, :url => sessions_path) do |f|
      - if @errors.present?
        - @errors.each do |msg|
          li
            font color="red"
              = msg

      .field
        = f.label :email, "Email or Login"
        = f.text_field :email
      .field
        = f.label :password
        = f.password_field :password
      .actions
        button type="button" class="btn btn-danger" data-dismiss="modal" aria-hidden="true" Close
        = f.submit "Log in", :class => "btn btn-success"
    p
      | New user?
      = link_to " Register now!", new_users_path, :remote=>true
    p
      = link_to "Log in with Twitter", "/auth/twitter"

app/views/application/_list.html.slim
= paginate @users

ul.users
  -@users.each do |user|
    li
      .row
        .span3
          = link_to gravatar_for(user), user, :remote => true
        .span9
          dl
            dt
              | Login
            dd
              = link_to user.login, user, :remote => true


= paginate @users

app/views/application/_navbar_actions.html.slim
.nav-collapse
  ul.nav
    li.active
      - if current_user.present?
        ul.nav
          li.dropdown
            a.dropdown-toggle href="" data-toggle="dropdown"
              |Account
              b.caret
            ul.dropdown-menu
              = link_to "Home",  profile_path, :remote => true
              = link_to "Edit", edit_path


      -else
        = link_to "Account", profile_path, :remote => true
    li
      = link_to "Users", index_path, :remote => true
      - if current_user.present?
        li
          = link_to "Log out", sessions_path, :remote => true, method: :delete, data: { confirm: 'Are you sure?' }
      - else
        li
          = link_to "Log in", new_sessions_path, :remote => true
        li
          = link_to "Register", new_users_path, :remote => true

app/views/application/_profile.html.slim
#profile
  h1
    = @user.login
  p
  = gravatar_for @user
  - if current_user?(@user)
    = @user.email
    = button_to "Edit", edit_path

app/views/application/_register_form.html.slim
a#modalButton href="#myModal" role="button" class="btn" data-toggle="modal" style="display:none"

#myModal.modal tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-header
    button type="button" id="closeButton" class="close" data-dismiss="modal" aria-hidden="true" &times
    h2 Register now!

  .modal-body
    = form_for(@user, :remote=>true) do |f|
      - if @user.errors.any?
        #error_explanation
          | Sorry, you have
          =" " + pluralize(@user.errors.count, "error")
          ul
            - @user.errors.full_messages.each do |msg|
              li
                = msg

      .field
        = f.label :login
        = f.text_field :login
      .field
        = f.label :email
        = f.text_field :email
      .field
        = f.label :password
        = f.password_field :password
      .field
        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation
      .actions
        button type="button" class="btn btn-danger" data-dismiss="modal" aria-hidden="true" Close
        = f.submit "Register", :class => "btn btn-success", :style => "margin-left:60"
    p
      | Already registered?
      = link_to " Log in!", new_sessions_path, :remote=>true
    p
      = link_to "Log in with Twitter", "/auth/twitter"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authorization</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= yield %>

</div>
</body>
</html>

app/views/layouts/application.html.slim
doctype
html
  head
  title Registration app
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  body
    div.container
      div.navbar
        div.navbar-inner
          div.container
            a.btn.btn-navbar data-bind={"toggle:'collapse', target:'.nav-collapse'"}
              span.icon-bar
              span.icon-bar
              span.icon-bar
            = link_to "Anton Jyha",  profile_path, :remote => true, :class => "brand"
            div#navbar_actions
              = render "navbar_actions"
      div#for_form
      div#page
        = yield

app/views/users/_form.html.slim
a#modalButton href="#myModal" role="button" class="btn" data-toggle="modal" style="display:none"

div#myModal.modal tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div.modal-header
    button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times
    | Register now!
  div.modal-body
    = form_for(@user) do |f|
      - if @user.errors.any?
        div#error_explanation
          h2
            | Sorry, you have
            = pluralize(@user.errors.count, "error")
          ul
            - @user.errors.full_messages.each do |msg|
              li
                = msg
            -
      -
      div.field
        = f.label :login
        = f.text_field :login
      div.field
        = f.label :email
        = f.text_field :email
      div.field
        = f.label :password
        = f.password_field :password
      div.field
        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation
      div.actions
        = f.submit "Register"

app/views/users/_profile.html.slim
div#profile
  h1
    | Hey,
    =" " + @user.login
  p
  = gravatar_for @user.email
  - if @user == current_user
    = @user.email
  -

app/views/users/edit.html.slim
= form_for current_user, :url => profile_path, :method => :put do |f|
  - if current_user.errors.any?
    - current_user.errors.full_messages.each do |msg|
      li
        = msg
  h2
    | Profile Edit
  .field
    = f.label :login
    = f.text_field :login
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = link_to "Cancel", profile_path, :class => "btn btn-danger"
    = f.submit "Apply", :class => "btn btn-success", :style => "margin-left:60"

app/views/users/form.js.erb
$('#closeButton').click();
$('#for_form').html("<%= escape_javascript(render :partial => "form") %>")
$('#modalButton').click();

app/views/users/index.html.slim
= render "list"

app/views/users/index.js.erb
$('#navbar_actions').html("<%= escape_javascript(render "navbar_actions") %>")
$('#page').html("<%= escape_javascript(render "list") %>")
window.history.pushState(""," ", "<%= escape_javascript(index_path) %>");

app/views/users/new.html.haml
%h1 Hello
%p Register now!
= form_for(@user) do |f|
  - if @user.errors.any?
    %div#error_explanation
      %h2
        Sorry, you have
        = pluralize(@user.errors.count, "error")
      %ul
        - @user.errors.full_messages.each do |msg|
          %li
            = msg
        -
  -

  %div.field
    = f.label :login
    = f.text_field :login
  %div.field
    = f.label :email
    = f.text_field :email
  %div.field
    = f.label :password
    = f.password_field :password
  %div.field
    = f.label :password_confirmation, "Confirmation"
    = f.password_field :password_confirmation
  %div.actions
    = f.submit "Sign up"
-
%p
  Already registered?
  = link_to "Log in!", new_sessions_path

app/views/users/new.html.slim
h2 Register now!
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      h2
        | Sorry, you have
        = pluralize(@user.errors.count, "error")
      ul
        - @user.errors.full_messages.each do |msg|
          li
            = msg

  .field
    = f.label :login
    = f.text_field :login
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation, "Confirmation"
    = f.password_field :password_confirmation
  .actions
    = f.submit "Register"
p
  | Already registered?
  = link_to " Log in!", new_sessions_path
p
  = link_to "Log in with Twitter", "/auth/twitter"

app/views/users/register_form.js.erb
$('#closeButton').click();
$('#for_form').html("<%= escape_javascript(render :partial => "register_form",:locals =>{ :user => User.new}) %>")
$('#modalButton').click();

app/views/users/show.html.slim
= render "profile"

app/views/users/show.js.erb
$('#closeButton').click();
$('#navbar_actions').html("<%= escape_javascript(render "navbar_actions") %>")
$('#page').html("<%= escape_javascript(render "profile") %>")
window.history.pushState(""," ", "<%= escape_javascript(user_path(@user||current_user)) %>");